// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSVaf5yAGRA5-sanf18k3FcAxkRSVDdYA',
    appId: '1:428599192434:web:a84c7127ee165a5084cbeb',
    messagingSenderId: '428599192434',
    projectId: 'quizword-75ffc',
    authDomain: 'quizword-75ffc.firebaseapp.com',
    storageBucket: 'quizword-75ffc.firebasestorage.app',
    measurementId: 'G-WW9646L3TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7rybDE5gbMN01mOzvbPWUqIPRgjnRBc',
    appId: '1:428599192434:android:a08369a8647dbb1884cbeb',
    messagingSenderId: '428599192434',
    projectId: 'quizword-75ffc',
    storageBucket: 'quizword-75ffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATU-dy1RftrCdGTHfij0vXgweCTivSzWw',
    appId: '1:428599192434:ios:3086493a2e33a46484cbeb',
    messagingSenderId: '428599192434',
    projectId: 'quizword-75ffc',
    storageBucket: 'quizword-75ffc.firebasestorage.app',
    iosBundleId: 'com.example.vocabStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATU-dy1RftrCdGTHfij0vXgweCTivSzWw',
    appId: '1:428599192434:ios:3086493a2e33a46484cbeb',
    messagingSenderId: '428599192434',
    projectId: 'quizword-75ffc',
    storageBucket: 'quizword-75ffc.firebasestorage.app',
    iosBundleId: 'com.example.vocabStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0H8ndZ_meY8Q7SixpT7JdLO6Hva68FKE',
    appId: '1:428599192434:web:e9940a124d86c33884cbeb',
    messagingSenderId: '428599192434',
    projectId: 'quizword-75ffc',
    authDomain: 'quizword-75ffc.firebaseapp.com',
    storageBucket: 'quizword-75ffc.firebasestorage.app',
    measurementId: 'G-HGVHRYHDL0',
  );
}
